name: Github Actions Demo
on: push
jobs:
  Example-job: 
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - run: echo "The ${{ github.repository }} repo has been cloned to the runner"

      - run: echo "Your repo has been copied to the path ${{ github.workspace }} on the runner"

      - name: conditional step when event is push
        if: ${{ github.event_name == 'push' }}
        run: echo "This is a push event"

      - name: List files in tools cache
        run: |
          ls ${{ runner.tool_cache }}

      - run: echo "This job's status is ${{ job.status }}"
